name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**/*'
      - 'test/**/*'

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24' 
    - run: |
        npm install -g @liriliri/lsla
        npm i
        npm run ci